-- add new table product
DROP TABLE IF EXISTS PRODUCT
;

CREATE TABLE PRODUCT (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRICE NUMERIC(10,2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
;